src/main/java/at/qe/sepm/skeleton/model/TimeStamp.java
package at.qe.sepm.skeleton.model;

import java.util.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.domain.Persistable;

/**
 * Entity representing timestamps.
 */
@Entity
public class TimeStamp implements Persistable<String> {

    private static final long serialVersionUID = 1L;

    @Id @GeneratedValue(strategy=GenerationType.AUTO)
    private Long timeStampId;

    private Date timeStampStart;
    
    private Date timeStampEnd;

	private Double time;
    
    @ManyToOne @JoinColumn(nullable = true, name="user")
    private User user;
    
    @ManyToOne @JoinColumn(nullable = true, name="workPackage")
    private WorkPackage workPackage;

    @Column(nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date createDate;    
    
    

    public Long getTimeStampId() {
		return timeStampId;
	}

	public void setTimeStampId(Long timeStampId) {
		this.timeStampId = timeStampId;
	}

	public Date getTimeStampStart() {
		return timeStampStart;
	}

	public void setTimeStampStart(Date timeStampStart) {
		this.timeStampStart = timeStampStart;
	}

	public Date getTimeStampEnd() {
		return timeStampEnd;
	}

	public void setTimeStampEnd(Date timeStampEnd) {
		this.timeStampEnd = timeStampEnd;
	}

	public Double getTime() {
		return time;
	}

	public void calcTime() {
		this.time = ((this.getTimeStampEnd().getTime() - this.getTimeStampStart().getTime()) / (double) (60*60*1000));
	}

	public User getUser() {
		return this.user;
	}
	
	public void setUser(User user) {
		this.user = user;
	}
    
    public WorkPackage getWorkPackage() {
		return workPackage;
	}

	public void setWorkPackage(WorkPackage workPackage) {
		this.workPackage = workPackage;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + Objects.hashCode(this.timeStampId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof TimeStamp)) {
            return false;
        }
        final TimeStamp other = (TimeStamp) obj;
        if (!Objects.equals(this.timeStampId, other.timeStampId)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "at.qe.sepm.skeleton.model.TimeStamp[ id=" + timeStampId + " ]";
    }

    @Override
    public String getId() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

	@Override
	public boolean isNew() {
		return (null == createDate);
	}


}

src/main/java/at/qe/sepm/skeleton/model/User.java
package at.qe.sepm.skeleton.model;

import java.util.Date;
import java.util.Objects;
import java.util.Set;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.domain.Persistable;

/**
 * Entity representing users.
 */
@Entity
public class User implements Persistable<String>, Comparable<User> {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(length = 100)
    private String username;

    @ManyToOne(optional = false)
    private User createUser;
    @Column(nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date createDate;
    @ManyToOne(optional = true)
    private User updateUser;
    @Temporal(TemporalType.TIMESTAMP)
    private Date updateDate;

    private String password;

    private String firstName;
    private String lastName;
    private String email;
    private String phone;

    boolean enabled;

    @ElementCollection(targetClass = UserRole.class, fetch = FetchType.EAGER)
    @CollectionTable(name = "User_UserRole")
    @Enumerated(EnumType.STRING)
    private Set<UserRole> roles;
    
    @ManyToOne @JoinColumn(nullable = true, name="projectTeam")
    private ProjectTeam projectTeam;

    @Enumerated(EnumType.STRING)
    private Layout design;

    
	public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = (username);
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
    	//PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
        //this.password =  passwordEncoder.encode(password);
    	this.password = password;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public Set<UserRole> getRoles() {
        return roles;
    }

    public void setRoles(Set<UserRole> roles) {
        this.roles = roles;
    }

    public User getCreateUser() {
        return createUser;
    }

    public void setCreateUser(User createUser) {
        this.createUser = createUser;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public User getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(User updateUser) {
        this.updateUser = updateUser;
    }

    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    public ProjectTeam getProjectTeam() {
		return projectTeam;
	}

	public void setProjectTeam(ProjectTeam projectTeam) {
		this.projectTeam = projectTeam;
	}
	
    public Layout getDesign() {
		return design;
	}

	public void setDesign(Layout design) {
		this.design = design;
	}


	@Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + Objects.hashCode(this.username);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof User)) {
            return false;
        }
        final User other = (User) obj;
        if (!Objects.equals(this.username, other.username)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "at.qe.sepm.skeleton.model.User[ id=" + username + " ]";
    }

    @Override
    public String getId() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean isNew() {
        return (null == createDate);
    }

	@Override
	public int compareTo(User o) {
		return this.username.compareTo(o.getUsername());
	}

}

src/main/java/at/qe/sepm/skeleton/ui/beans/SessionInfoBean.java
package at.qe.sepm.skeleton.ui.beans;

import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.model.UserRole;
import at.qe.sepm.skeleton.services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;

/**
 * Session information bean to retrieve session-specific parameters.
 *
 * @author Michael Brunner <Michael.Brunner@uibk.ac.at>
 */
@Component
@Scope("session")
public class SessionInfoBean {

	@Autowired
	private UserService userService;

	/**
	 * Attribute to cache the current user.
	 */
	private User currentUser;

	/**
	 * Returns the currently logged on user, null if no user is authenticated
	 * for this session.
	 *
	 * @return
	 */
	public User getCurrentUser() {
		String currentUserName = getCurrentUserName();
		if (   currentUser == null
			|| currentUser.getUsername() != currentUserName) {
			if (currentUserName.isEmpty()) {
				return null;
			}
			currentUser = userService.loadUser(currentUserName);
		}
		return currentUser;
	}

	/**
	 * Returns the username of the user for this session, empty string if no
	 * user has been authenticated for this session.
	 *
	 * @return
	 */
	public String getCurrentUserName() {
		if (!isLoggedIn()) {
			return "";
		}
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		String name = auth.getName(); // get logged in username
		return name;
	}

	/**
	 * Returns the roles of the user for this session as space-separated list,
	 * empty string if no user has been authenticated for this session-
	 *
	 * @return
	 */
	public String getCurrentUserRoles() {
		if (!isLoggedIn()) {
			return "";
		}
		StringBuilder sb = new StringBuilder();
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		for (GrantedAuthority role : auth.getAuthorities()) {
			sb.append(role.getAuthority());
			sb.append(' ');
		}
		return sb.toString().trim();
	}

	/**
	 * Checks if a user is authenticated for this session.
	 *
	 * @return true if a non-anonymous user has been authenticated, false
	 *         otherwise
	 */
	public boolean isLoggedIn() {
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (auth != null) {
			return auth.isAuthenticated() && !auth.getName().equals("anonymousUser");
		} else {
			return false;
		}
	}

	/**
	 * Checks if the user for this session has the given role (c.f.
	 * {@link UserRole}).
	 *
	 * @param role
	 *            the role to check for as string
	 * @return true if a user is authenticated and the current user has the
	 *         given role, false otherwise
	 */
	public boolean hasRole(String role) {
		if (role == null || role.isEmpty() || !isLoggedIn()) {
			return false;
		}
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		for (GrantedAuthority ga : auth.getAuthorities()) {
			if (role.equals(ga.getAuthority())) {
				return true;
			}
		}
		return false;
	}

	public String getDesign(){
                
		return userService.getUserDesign(getCurrentUser());
	}
	
}

src/main/java/at/qe/sepm/skeleton/ui/beans/TimeStampBean.java
package at.qe.sepm.skeleton.ui.beans;

import at.qe.sepm.skeleton.model.TimeStamp;
import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.services.TimeStampService;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author daniel
 */

@Component
@Scope("request")
public class TimeStampBean {
    
    @Autowired
    private TimeStampService timeStampService;
    
    @Autowired
    private SessionInfoBean sessionInfo;
    
    public boolean hasOpenTimeStamp(){
            return hasOpenTimeStamp4User(sessionInfo.getCurrentUser());
    }
    
    public boolean hasOpenTimeStamp4User(User user){
        return timeStampService.getOpenTimeStamp4User(user) != null;
    }
    
    public TimeStamp getOpenTimeStamp(){
        return timeStampService.getOpenTimeStamp4User(sessionInfo.getCurrentUser());
    }
    
    public List<TimeStamp> getStamps4User(User user){
        return this.timeStampService.findByUser(user);
    }
}

src/main/java/at/qe/sepm/skeleton/ui/controllers/ProjectTeamListController.java
package at.qe.sepm.skeleton.ui.controllers;

import java.util.Collection;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import at.qe.sepm.skeleton.model.ProjectTeam;
import at.qe.sepm.skeleton.services.ProjectTeamService;
import at.qe.sepm.skeleton.ui.beans.SessionInfoBean;

/**
 * Controller for the project list view.
 *
 * @author Robert Schaffenrath
 */
@Component
@Scope("view")
public class ProjectTeamListController {

    @Autowired
    private ProjectTeamService projectTeamService;
    @Autowired
    private SessionInfoBean sessionInfo;

    /**
     * Returns a list of all projects.
     *
     * @return
     */
    public Collection<ProjectTeam> getProjects() {
        return projectTeamService.loadAllProjects4Moderator(sessionInfo.getCurrentUser());
    }
    
    public Collection<ProjectTeam> getAdminProjects() {
        return projectTeamService.getAllProjects();
    }

}

src/main/webapp/admin/projects.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name ="content">
        <h:form id="userForm">
        
        	
            
            <p:dataTable id="workPackage" var="workPackage" value="#{workPackageListController.packages}">
                <p:column headerText="WorkPackageId">
                    <h:outputText value="#{workPackage.workPackageId}"/>
                </p:column>
                <p:column headerText="WorkPackageName">
                    <h:outputText value="#{workPackage.workPackageName}"/>
                </p:column>
                <p:column class="icons">
                    <p:commandButton update=":userForm:workPackageEditDialog" oncomplete="PF('workPackageEditDialog').show()" icon="ui-icon-pencil" title="Edit">
                        <f:setPropertyActionListener value="#{workPackage}" target="#{workPackageDetailController.workPackage}" />
                    </p:commandButton>
                </p:column>
            </p:dataTable>
            
            <p:dialog header="Edit Work Package" id="workPackageEditDialog" widgetVar="workPackageEditDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                <p:outputPanel id="workPackageData" rendered="#{not empty workPackageDetailController.workPackage}">
                    <h:panelGrid columns="2">
                        <p:outputLabel for="workPackageName" value="Work Package Name: " />
                        <p:inputText id="workPackageName" value="#{workPackageDetailController.workPackage.workPackageName}" disabled="false"/>
                    </h:panelGrid>
                    <h:panelGrid columns="3">
                        <p:commandButton value="Save" action="#{workPackageDetailController.doSaveWorkPackage()}" oncomplete="PF('projectTeamEditDialog').hide()" update=":userForm"/>
                        <p:commandButton value="Reload" action="#{workPackageDetailController.doReloadWorkPackage()}" update=":userForm:workPackageData"/>
                        <p:commandButton value="Abort" onclick="PF('workPackageEditDialog').hide()"/>
                    </h:panelGrid>
                </p:outputPanel>
            </p:dialog>
            
        
           
            

        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/admin/teams.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name ="content">
        <h:form id="userForm">
        
        	<p:dataTable id="ProjectTeam" var="projectTeam" value="#{projectTeamListController.adminProjects}">
                <p:column headerText="ProjectTeamId">
                    <h:outputText value="#{projectTeam.projectTeamId}"/>
                </p:column>
                <p:column headerText="ProjectTeamName">
                    <h:outputText value="#{projectTeam.projectTeamName}"/>
                </p:column>
                <p:column headerText="Moderator">
                    <h:outputText value="#{projectTeam.moderator.username}"/>
                </p:column>
                <p:column class="icons">
                    <p:commandButton update=":userForm:projectTeamEditDialog" oncomplete="PF('projectTeamEditDialog').show()" icon="ui-icon-pencil" title="Edit">
                        <f:setPropertyActionListener value="#{projectTeam}" target="#{projectTeamDetailController.projectTeam}" />
                    </p:commandButton>
                </p:column>
            </p:dataTable>
            
            <p:dialog header="Edit Project Team" id="projectTeamEditDialog" widgetVar="projectTeamEditDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                <p:outputPanel id="projectTeamData" rendered="#{not empty projectTeamDetailController.projectTeam}">
                    <h:panelGrid columns="2">
                        <p:outputLabel for="projectTeamName" value="Teamname: " />
                        <p:inputText id="projectTeamName" value="#{projectTeamDetailController.projectTeam.projectTeamName}" disabled="false"/>
                    </h:panelGrid>
                    <h:panelGrid columns="2">
                        <p:outputLabel for="moderator" value="Moderator: " />
                        <p:selectOneMenu id="moderator" value="#{projectTeamDetailController.projectTeam.moderator.username}" style="width: 165px">
                        	<f:selectItem itemLabel="Select moderator" itemValue="#{null}" noSelectionOption="true" itemDisabled="true"/>
                			<f:selectItems value="#{userListController.users}" var="mods" itemValue="#{mods.username}" itemLabel="#{mods.username}" />
            			</p:selectOneMenu>
                    </h:panelGrid>
                    <h:panelGrid columns="3">
                        <p:commandButton value="Save" action="#{projectTeamDetailController.doSaveProjectTeam()}" oncomplete="PF('projectTeamEditDialog').hide()" update=":userForm"/>
                        <p:commandButton value="Reload" action="#{projectTeamDetailController.doReloadProjectTeam()}" update=":userForm:projectTeamData"/>
                        <p:commandButton value="Abort" onclick="PF('projectTeamEditDialog').hide()"/>
                    </h:panelGrid>
                </p:outputPanel>
            </p:dialog>
            
            

            

        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/admin/timestamps.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name ="content">
        <h:form id="userForm">
        
        	
            
            <p:dataTable id="TimeStampTable" var="timeStamp" value="#{timeStampListController.stamps}">
                <p:column headerText="TimeStampId">
                    <h:outputText value="#{timeStamp.timeStampId}"/>
                </p:column>
                <p:column headerText="TimeStampStart">
                    <h:outputText value="#{timeStamp.timeStampStart}"/>
                </p:column>
                <p:column headerText="TimeStampEnd">
                    <h:outputText value="#{timeStamp.timeStampEnd}"/>
                </p:column>
                <p:column headerText="TimeStampTime">
                    <h:outputText value="#{timeStamp.time}"/>
                </p:column>
                <p:column headerText="WorkPackageName">
                    <h:outputText value="#{timeStamp.workPackage.workPackageName}"/>
                </p:column>
                <p:column headerText="username">
                    <h:outputText value="#{timeStamp.user.username}"/>
                </p:column>
                <p:column class="icons">
                    <p:commandButton action="#{timeStampDetailController.doDeleteTimeStamp}" icon="ui-icon-trash" title="Delete" update=":userForm">
                        <f:setPropertyActionListener value="#{timeStamp}" target="#{timeStampDetailController.timeStamp}" />
                        <p:confirm header="Confirmation" message="Are you sure that you want to delete this TimeStamp? You cannot undo this operation." icon="ui-icon-alert" />
                    </p:commandButton>
                </p:column>
            </p:dataTable>
            
            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade" width="300">
                <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
            </p:confirmDialog>

            

        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/admin/users.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name ="content">
        <h:form id="userForm">

            <p:dataTable id="usersTable" var="user" value="#{userListController.users}">
                <p:column headerText="Username">
                    <h:outputText value="#{user.username}"/>
                </p:column>
                <p:column headerText="First Name">
                    <h:outputText value="#{user.firstName}"/>
                </p:column>
                <p:column headerText="Last Name">
                    <h:outputText value="#{user.lastName}"/>
                </p:column>
                <p:column headerText="Roles">
                    <h:outputText value="#{user.roles}" />
                </p:column>
                <p:column headerText="ProjectTeam">
                    <h:outputText value="#{user.projectTeam.projectTeamName}" />
                </p:column>
                <p:column headerText="Enabled">
                    <h:selectBooleanCheckbox value="#{user.enabled}" disabled="true"/>
                </p:column>
                <p:column headerText="Design">
                    <h:outputText value="#{user.design}" />
                </p:column>
                <p:column headerText="Email">
                    <h:outputText value="#{user.email}" />
                </p:column>
                <p:column headerText="updated">
                    <h:outputText value="#{user.updateDate}" />
                </p:column>
                <p:column headerText="updated by">
                    <h:outputText value="#{user.updateUser.username}" />
                </p:column>
                <p:column class="icons">
                    <p:commandButton update=":userForm:userEditDialog" oncomplete="PF('userEditDialog').show()" icon="ui-icon-pencil" title="Edit">
                        <f:setPropertyActionListener value="#{user}" target="#{userDetailController.user}" />
                    </p:commandButton>
                    <p:commandButton action="#{userDetailController.doDeleteUser}" icon="ui-icon-trash" title="Delete" update=":userForm">
                        <f:setPropertyActionListener value="#{user}" target="#{userDetailController.user}" />
                        <p:confirm header="Confirmation" message="Are you sure that you want to delete this user? You cannot undo this operation." icon="ui-icon-alert" />
                    </p:commandButton>
                </p:column>
            </p:dataTable>
           

            <p:dialog header="Edit User" id="userEditDialog" widgetVar="userEditDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                <p:outputPanel id="userData" rendered="#{not empty userDetailController.user}">
                    <h:panelGrid columns="2">
                        <p:outputLabel for="username" value="Username: " />
                        <p:inputText id="username" value="#{userDetailController.user.username}" disabled="true"/>
                        <p:outputLabel for="password" value="Password: " />
                        <p:password id="password" value="#{userDetailController.user.password}" disabled="true"/>
                    </h:panelGrid>
                    <p:separator />
                    <h:panelGrid columns="2">
                        <p:outputLabel for="firstName" value="First Name: " />
                        <p:inputText id="firstName" value="#{userDetailController.user.firstName}"/>
                        <p:outputLabel for="firstName" value="Last Name: " />
                        <p:inputText id="lastName" value="#{userDetailController.user.lastName}"/>
                        <p:outputLabel for="email" value="E-Mail: " />
                        <p:inputText id="email" value="#{userDetailController.user.email}"/>
                        <p:outputLabel for="phone" value="Phone: " />
                        <p:inputMask id="phone" value="#{userDetailController.user.phone}" mask="+99? 999 9999999"/>
                    </h:panelGrid>
                    <p:separator />
                    <h:panelGrid columns="2">
                        <p:outputLabel for="enabled" value="Enabled: " />
                        <p:selectBooleanCheckbox id="enabled" value="#{userDetailController.user.enabled}"/>
                    </h:panelGrid>
                    <h:panelGrid columns="2">
                        <p:outputLabel for="projectTeam" value="ProjectTeam: " />
                        <p:selectOneMenu id="projectTeam" value="#{userDetailController.user.projectTeam.projectTeamId}" style="width: 165px">
                        	<f:selectItem itemLabel="Select ProjectTeam" itemValue="#{null}" noSelectionOption="true" itemDisabled="true"/>
                			<f:selectItems value="#{projectTeamListController.adminProjects}" var="projects" itemValue="#{projects.projectTeamId}" itemLabel="#{projects.projectTeamName}" />
            			</p:selectOneMenu>
                    </h:panelGrid>
                    <p:separator />
                    <h:panelGrid columns="3">
                        <p:commandButton value="Save" action="#{userDetailController.doSaveUser()}" oncomplete="PF('userEditDialog').hide()" update=":userForm"/>
                        <p:commandButton value="Reload" action="#{userDetailController.doReloadUser()}" update=":userForm:userData"/>
                        <p:commandButton value="Abort" onclick="PF('userEditDialog').hide()"/>
                    </h:panelGrid>
                </p:outputPanel>
            </p:dialog>

            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade" width="300">
                <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
            </p:confirmDialog>
            
           

            

        </h:form>
    </ui:define>
</ui:composition>