src/main/java/at/qe/sepm/skeleton/ui/controllers/ProjectTeamDetailController.java
package at.qe.sepm.skeleton.ui.controllers;

import at.qe.sepm.skeleton.model.ProjectTeam;
import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.model.WorkPackage;
import at.qe.sepm.skeleton.services.ProjectTeamService;
import at.qe.sepm.skeleton.services.UserService;
import at.qe.sepm.skeleton.ui.beans.SessionInfoBean;
import at.qe.sepm.skeleton.utils.TeamOverviewData;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 * Controller for the project detail view.
 *
 * @author Robert Schaffenrath
 */
@Component
@Scope("view")
public class ProjectTeamDetailController {

    @Autowired
    private ProjectTeamService projectService;
    
    @Autowired
    private UserService userService;
    
    @Autowired
    private SessionInfoBean sessionBean;

    /**
     * Attribute to cache the currently selected projectTeam
     */
    private ProjectTeam projectTeam;
    
    /**
     * Attribute to cache the currently selected projectTeamName
     * used for selectOneMenu
     */
    private String selectName;

    /**
     * Returns the currently selected project.
     *
     * @return
     */
    public ProjectTeam getProjectTeam() {
        return projectTeam;
    }

    /**
     * Returns the currently selected projectTeamName
     * @return 
     */
    public String getSelectName() {
        return selectName;
    }

    /**
     * Sets the projectTeamName
     * selectOneMenu saves projectTeamName
     * @param selectName 
     */
    public void setSelectName(String selectName) {
        this.selectName = selectName;
    }

    /**
     * Sets the currently displayed projectTeam and reloads it form db. This projectTeam is
     * targeted by any further calls of
     * {@link #doReloadProjectTeam()}, {@link #doSaveProjectTeam()} and
     * {@link #doDeleteProjectTeam()}.
     *
     * @param projectTeam
     */
    
    public void setProjectTeam(ProjectTeam projectTeam) {
        this.projectTeam = projectTeam;
        doReloadProjectTeam();
    }

    
    public void doLoadProjectTeamByName(){
        this.projectTeam = projectService.loadProject(selectName);
    }

    public void doDeleteProjectTeam() {
        this.projectService.deleteProjectTeam(projectTeam);
        projectTeam = null;
    }
    
    public void doSaveProjectTeam() {
        projectTeam = this.projectService.saveProjectTeam(projectTeam);
    }

    /**
     * Action to force a reload of the currently displayed projectTeam.
     */
    public void doReloadProjectTeam() {
        projectTeam = projectService.loadProject(projectTeam.getProjectTeamName());
    }
    
    /**
     * Converts overview data from service to Set of work package name and 
     * total time
     * @return 
     */
    public Set<Map.Entry<String, Double>> getOverview4ProjectTeam() {
        if (this.projectTeam != null) {
            Map<WorkPackage, TeamOverviewData> userProjectSet = projectService.getOverview4ProjectTeam(this.projectTeam);
            Set<WorkPackage> keys = userProjectSet.keySet();
            Map<String, Double> outputMap = new TreeMap<>();
            for (WorkPackage key : keys) {
                    outputMap.put(key.getWorkPackageName(), userProjectSet.get(key).getTimeSum());
            }
            return outputMap.entrySet();
            //return new ArrayList<>(outputMap.entrySet());
        } else {
            return null;
        }
    }
    
    /**
     * Return Set of workPackage and teamOveriewData for specific project team
     * Method is necesary for the pieChart in the ChartController
     * @param team
     * @return 
     */
    public Set<Map.Entry<WorkPackage, TeamOverviewData>> getOverview4PiChart(ProjectTeam team){
        if (team != null){
            return projectService.getOverview4ProjectTeam(team).entrySet();
        }
        else{
            return null;
        }
    }
    
    /**
     * Checks if there is currently a projectTeam saved in this controller
     * @return true if projectTeams is saved, false otherwise 
     */
    public boolean isProjectSelected() {
        return this.projectTeam != null;
    }
    
    /**
     * Returns a list of all project teams
     * @return 
     */
    public List<ProjectTeam> getProjectTeams() {
        return projectService.loadAllProjects4Moderator(sessionBean.getCurrentUser());
    }
    
    /**
     * Returns set of all users, who are working on the currently saved project
     * @return 
     */
    public Set<User> getUserForProjectTeam() {      
        List<ProjectTeam> teams = getProjectTeams();
        
        //updated by GOGLDA - Instead of List used SortedSet
        Set<User> teamUsers = new TreeSet<>();
        for (ProjectTeam t : teams) {
            teamUsers.addAll(userService.getUser4ProjectTeam(t));
        }
        teamUsers.add(sessionBean.getCurrentUser());
        
        return teamUsers;
                
    }
    
}

src/main/java/at/qe/sepm/skeleton/ui/controllers/UserDetailController.java
package at.qe.sepm.skeleton.ui.controllers;

import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.model.WorkPackage;
import at.qe.sepm.skeleton.services.UserService;
import at.qe.sepm.skeleton.ui.beans.SessionInfoBean;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 * Controller for the user detail view.
 *
 * @author Robert Schaffenrath
 */
@Component
@Scope("view")
public class UserDetailController {

	@Autowired
	private UserService userService;

	@Autowired
	private SessionInfoBean sessionBean;

	/**
	 * Attribute to cache the currently selected user
	 */
	private User user;

	/**
	 * Attribute to cache the currently selected username used for selectOneMenu
	 */
	private String selectName;

	/**
	 * Returns the currently selected user.
	 *
	 * @return
	 */
	public User getUser() {
		return user;
	}

	/**
	 * Returns the currently selected username Used to load user for
	 * selectOneMenu
	 * 
	 * @return
	 */
	public String getUserName() {
		return selectName;
	}

	/**
	 * Sets the username selectOneMenu saves username
	 * 
	 * @param userName
	 */
	public void setUserName(String userName) {
		this.selectName = userName;
	}

	/**
	 * Action to load user by username used for selectOneMenu to select user
	 */
	public void doLoadUserByName() {
		if (this.selectName != null) {
                    this.user = userService.loadUser(selectName);
		}
	}

	/**
	 * Sets the currently displayed user and reloads it form db. This user is
	 * targeted by any further calls of {@link #doReloadUser()},
	 * {@link #doSaveUser()} and {@link #doDeleteUser()}.
	 *
	 * @param user
	 */
	public void setUser(User user) {
		this.user = user;
		doReloadUser();
	}

	/**
	 * Action to force a reload of the currently displayed user.
	 */
	public void doReloadUser() {
		user = userService.loadUser(user.getUsername());
	}

	/**
	 * Action to save the currently selected user.
	 */
	public void doSaveUser() {
		user = this.userService.saveUser(user);
	}

	/**
	 * Action to delete the currently selected user.
	 */
	public void doDeleteUser() {
		this.userService.deleteUser(user);
		user = null;
	}

	/**
	 * Action loads workPackage and Time for saved user and converts it to
	 * Set of Entries for dataTable
	 * 
	 * @return
	 */
	public Set<Map.Entry<String, Double>> getOverview4User() {
		if (this.user != null) {
			Map<WorkPackage, Double> userProjectSet = userService.getOverview4User(this.user);
			Set<WorkPackage> keys = userProjectSet.keySet();
			Map<String, Double> outputMap = new TreeMap<>();
			for (WorkPackage key : keys) {
				Long hours = Math.round(userProjectSet.get(key) * 100);
				Double rounded = hours.doubleValue() / 100;

				outputMap.put(key.getWorkPackageName(), rounded);
			}
			return outputMap.entrySet();
		} else {
			return null;
		}
	}

	/**
	 * Checks if overview4Users is loaded or available
	 * 
	 * @return true if overview4Users is available and loaded, false otherwise
	 */
	public boolean isUserSelected() {
		return this.user != null;
	}

	public List<String> getDesigns() {
		return userService.getAllDesigns();
	}

	public String getDesign() {
		return userService.getUserDesign(sessionBean.getCurrentUser());
	}

	public void setDesign(String design) {
		userService.setUserDesign(sessionBean.getCurrentUser(), design);
	}
}

src/main/webapp/student/group_statistics.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:ng="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name ="content">
        <h:form>

            <!-- Selection Menu for GroupStatistics -->
            <p:panel>
                <h:panelGrid columns="1" cellpadding="2" class="statistics">
                    <p:row>
                        <p:outputLabel value="Teams:"/>
                    </p:row>
                    <p:row>
                        <p:column>
                            <p:selectOneMenu id="projectSelect" value="#{projectTeamDetailController.selectName}" style="width: 250px" filter="true" filterMatchMode="startsWith">   
                                <f:selectItem itemLabel="Select team" itemValue="#{null}" noSelectionOption="true"/>
                                <f:selectItems value="#{projectTeamListController.projects}" var="projects" itemValue="#{projects.projectTeamName}" itemLabel="#{projects.projectTeamName}" rendered="#{projects.projectTeamId ne 0}"/>
                                <p:ajax process="@this" update="@(form)" listener="#{projectTeamDetailController.doLoadProjectTeamByName()}"/>
                                <p:ajax listener="#{chartController.onGroupComplete(projectTeamDetailController.projectTeam)}"/>
                            </p:selectOneMenu>
                        </p:column>
                    </p:row>
                </h:panelGrid>
            </p:panel>

            <!-- DataTable for GroupStatistics -->
            <p:dataTable var="workPackage" value="#{projectTeamDetailController.getOverview4ProjectTeam()}" rendered="#{projectTeamDetailController.projectSelected}">
                <p:column headerText="Work package">
                    <h:outputText value="#{workPackage.key}"/>
                </p:column>
                <p:column headerText="Time [h]">
                    <h:outputText value="#{workPackage.value}"  class="right">
                        <f:convertNumber minFractionDigits="2" locale="en-US"/>
                    </h:outputText>
                </p:column>
            </p:dataTable>                

            <!--Group statistic graph-->

            <p:chart id="chart" type="bar" model="#{chartController.groupChart}" rendered="#{chartController.groupChartLoaded}" class="graph" style="height: #{chartController.height}px">
                <h:outputScript>
                    function chartExtender() {        
                    // this = chart widget instance        
                    // this.cfg = options      
                    this.cfg.seriesDefaults.rendererOptions.varyBarColor = true;
                    }
                </h:outputScript>
            </p:chart>

            <!--Pie chart for total Project Team-->

            <p:chart type="pie" model="#{chartController.groupPieChart}" class="graph" rendered="#{chartController.groupChartLoaded}" />	

            <!--Pie chart models for each Workpackage-->
            <p:dataGrid id="piChartGrid" var="charts" value="#{chartController.groupWpPieCharts}" columns="2" class="graph" rendered="#{chartController.groupChartLoaded}">
                <p:chart type="pie" model="#{charts}" />    
            </p:dataGrid>

        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/student/user_statistics.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name ="content">
        <h:form id="userForm">


            <!--Student selection selectOneMenu for admin -->
            <p:panel rendered="#{sessionInfoBean.hasRole('ADMIN')}">
                <h:panelGrid columns="1" cellpadding="2" class="statistics">
                    <p:row>
                        <p:outputLabel value="Students:"/>
                    </p:row>
                    <p:row>
                        <p:column>
                            <p:selectOneMenu id="studentSelect" value="#{userDetailController.userName}" style="width: 250px" filter="true" filterMatchMode="startsWith">
                                <f:selectItem itemLabel="Select student" itemValue="#{null}" noSelectionOption="true" rendered="false"/>
                                <f:selectItems value="#{userListController.users}" var="students" itemValue="#{students.username}" itemLabel="#{students.username}" />
                                <p:ajax process="@this" update="@(form)" listener="#{userDetailController.doLoadUserByName()}" oncomplete="#{chartController.createUserChart(userDetailController.user)}"/>
                            </p:selectOneMenu>

                        </p:column>
                    </p:row>
                </h:panelGrid>
            </p:panel>

            <!--Student selection selectOneMenu for moderator -->
            <p:panel rendered="#{(sessionInfoBean.hasRole('MODERATOR') and !(sessionInfoBean.hasRole('ADMIN')))}">
                <h:panelGrid columns="1" cellpadding="2" class="statistics">
                    <p:row>
                        <p:outputLabel value="Students:"/>
                    </p:row>
                    <p:row>
                        <p:column>

                            <p:selectOneMenu id="studentSelectMod" value="#{userDetailController.userName}" style="width: 250px" filter="true" filterMatchMode="startsWith">
                                <f:selectItem itemLabel="Select student" itemValue="#{null}" noSelectionOption="true" rendered="false"/>
                                <f:selectItems value="#{projectTeamDetailController.userForProjectTeam}" var="projectStudents" itemValue="#{projectStudents.username}" itemLabel="#{projectStudents.username}" />
                                <p:ajax process="@this" update="@(form)" listener="#{userDetailController.doLoadUserByName()}" oncomplete="#{chartController.createUserChart(userDetailController.user)}"/>
                            </p:selectOneMenu>
                        </p:column>
                    </p:row>
                </h:panelGrid>
            </p:panel>

            <h:form rendered="#{!(sessionInfoBean.hasRole('MODERATOR'))}">
                #{userDetailController.setUser(sessionInfoBean.currentUser)}
                #{chartController.createUserChart(userDetailController.user)}
            </h:form>

            <!--student dataTable with project name and time-->
            <p:dataTable var="workPackage" value="#{userDetailController.getOverview4User()}" rendered="#{userDetailController.userSelected}">
                <p:column headerText="Work Package">
                    <h:outputText value="#{workPackage.key}"/>
                </p:column>
                <p:column headerText="Time [h]">
                    <h:outputText value="#{workPackage.value}"  class="right">
                        <f:convertNumber minFractionDigits="2" locale="en-US"/>
                    </h:outputText>
                </p:column>
            </p:dataTable>

            <!--User statistic graph-->
            <p:chart id="chart" type="bar" model="#{chartController.userChart}" rendered="#{chartController.userChartLoaded}" class="graph" style="height: #{chartController.height}px">
                <h:outputScript>
                    function chartExtender() {        
                    // this = chart widget instance        
                    // this.cfg = options      
                    this.cfg.seriesDefaults.rendererOptions.varyBarColor = true;
                    }
                </h:outputScript>
            </p:chart>
        </h:form>
    </ui:define>
</ui:composition>