src/main/java/at/qe/sepm/skeleton/ui/controllers/UserDetailController.java
package at.qe.sepm.skeleton.ui.controllers;

import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.model.WorkPackage;
import at.qe.sepm.skeleton.services.UserService;
import at.qe.sepm.skeleton.ui.beans.SessionInfoBean;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 * Controller for the user detail view.
 *
 * @author Robert Schaffenrath
 */
@Component
@Scope("view")
public class UserDetailController {

	@Autowired
	private UserService userService;

	@Autowired
	private SessionInfoBean sessionBean;

	/**
	 * Attribute to cache the currently selected user
	 */
	private User user;

	/**
	 * Attribute to cache the currently selected username used for selectOneMenu
	 */
	private String selectName;

	/**
	 * Returns the currently selected user.
	 *
	 * @return
	 */
	public User getUser() {
		return user;
	}

	/**
	 * Returns the currently selected username Used to load user for
	 * selectOneMenu
	 * 
	 * @return
	 */
	public String getUserName() {
		return selectName;
	}

	/**
	 * Sets the username selectOneMenu saves username
	 * 
	 * @param userName
	 */
	public void setUserName(String userName) {
		this.selectName = userName;
	}

	/**
	 * Action to load user by username used for selectOneMenu to select user
	 */
	public void doLoadUserByName() {
		if (this.selectName != null) {
                    this.user = userService.loadUser(selectName);
		}
	}

	/**
	 * Sets the currently displayed user and reloads it form db. This user is
	 * targeted by any further calls of {@link #doReloadUser()},
	 * {@link #doSaveUser()} and {@link #doDeleteUser()}.
	 *
	 * @param user
	 */
	public void setUser(User user) {
		this.user = user;
		doReloadUser();
	}

	/**
	 * Action to force a reload of the currently displayed user.
	 */
	public void doReloadUser() {
		user = userService.loadUser(user.getUsername());
	}

	/**
	 * Action to save the currently selected user.
	 */
	public void doSaveUser() {
		user = this.userService.saveUser(user);
	}

	/**
	 * Action to delete the currently selected user.
	 */
	public void doDeleteUser() {
		this.userService.deleteUser(user);
		user = null;
	}

	/**
	 * Action loads workPackage and Time for saved user and converts it to
	 * Set of Entries for dataTable
	 * 
	 * @return
	 */
	public Set<Map.Entry<String, Double>> getOverview4User() {
		if (this.user != null) {
			Map<WorkPackage, Double> userProjectSet = userService.getOverview4User(this.user);
			Set<WorkPackage> keys = userProjectSet.keySet();
			Map<String, Double> outputMap = new TreeMap<>();
			for (WorkPackage key : keys) {
				Long hours = Math.round(userProjectSet.get(key) * 100);
				Double rounded = hours.doubleValue() / 100;

				outputMap.put(key.getWorkPackageName(), rounded);
			}
			return outputMap.entrySet();
		} else {
			return null;
		}
	}

	/**
	 * Checks if overview4Users is loaded or available
	 * 
	 * @return true if overview4Users is available and loaded, false otherwise
	 */
	public boolean isUserSelected() {
		return this.user != null;
	}

	public List<String> getDesigns() {
		return userService.getAllDesigns();
	}

	public String getDesign() {
		return userService.getUserDesign(sessionBean.getCurrentUser());
	}

	public void setDesign(String design) {
		userService.setUserDesign(sessionBean.getCurrentUser(), design);
	}
}

src/main/java/at/qe/sepm/skeleton/ui/controllers/WorkPackageDetailController.java
package at.qe.sepm.skeleton.ui.controllers;

import at.qe.sepm.skeleton.model.WorkPackage;
import at.qe.sepm.skeleton.services.TimeStampService;
import at.qe.sepm.skeleton.services.WorkPackageService;
import at.qe.sepm.skeleton.ui.beans.SessionInfoBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 * Controller for the workPackage detail view.
 *
 * @author Robert Schaffenrath
 */
@Component
@Scope("view")
public class WorkPackageDetailController {

    @Autowired
    private WorkPackageService workService;
    
    @Autowired
    private TimeStampService timeStampService;
    
    @Autowired
    private SessionInfoBean sessionInfo;

    /**
     * Attribute to cache the currently selected workPackage
     */
    private WorkPackage workPackage;
    
    /**
     * Attribute to cache the currently selected workPackageId
     */
    private Long selectedId; 

    /**
     * Sets the workPackage 
     * @param workPackage 
     */
    public void setWorkPackage(WorkPackage workPackage) {
        this.workPackage = workPackage;
        doReloadWorkPackage();
    }

    /**
     * Returns the currently selected workPackage
     * @return 
     */
    public WorkPackage getWorkPackage() {
        return workPackage;
    }
    
    /**
     * Sets the currently selected workPackage by id
     * selectOneMenu saves workPackageId
     * @param id 
     */
    public void setWorkPackageId(Long id){
        this.selectedId=id;
    }
    
    /**
     * Returns the currently selected username
     * Used to load workPackage for selectOneMenu
     * @return 
     */
    public Long getWorkPackageId(){
        return this.selectedId;
    }
    
    /**
     * Action loads workPackage by id
     * used for selectOneMenu to select workPackage
     */
    public void loadWorkPackageWithId(){
        this.setWorkPackage(workService.loadPackageWithId(selectedId));
    }
    
    
    /**
     * Sets the currently selected workPackage and reloads it form db. This workPackage is
     * targeted by any further calls of
     * {@link #doReloadWorkPackage()}, {@link #checkIn()} and
     * {@link #checkOut()}.
     *
     * @param user
     */
    
    /**
     * Action to force a reload of the currently displayed workPackage.
     */
    public void doReloadWorkPackage() {
        workPackage = workService.loadPackageWithName(workPackage.getWorkPackageName());
    }
    
    
    /**
     * Action to create starting timeStamp with selected workPackage
     */
    public void checkIn(){
        if(this.workPackage != null)
            timeStampService.checkIn(this.workPackage, sessionInfo.getCurrentUser());
    }
    
    /**
     * Action to creat closing timeStamp for starting timeStamp
     */
    public void checkOut(){
        timeStampService.checkOut(timeStampService.getOpenTimeStamp4User(sessionInfo.getCurrentUser()));
    }
    
    /**
     * Returns the name of the work package for the currently open timeStamp for the 
     * logged in user 
     * @return 
     */
    public String getOpenWorkPackageName() {
        return timeStampService.getOpenTimeStamp4User(sessionInfo.getCurrentUser()).getWorkPackage().getWorkPackageName();
    }
    
    /**
     * Sets the currently saved workPakage to null
     */
    public void doDeleteWorkPackage() {
        this.workService.deleteWorkPackage(workPackage);
        workPackage = null;
    }
    
    /**
     * Saves the currently saved workPackage via the service
     */
    public void doSaveWorkPackage() {
        workPackage = this.workService.saveWorkPackage(workPackage);
    }
}

src/main/webapp/secured/settings.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:ng="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name ="content">
        <h:form id="userForm">
            
            <p:panel> 

                    <h:panelGrid columns="2" cellpadding="5">
                        <p:outputLabel for="username" value="Username: " />
                        <p:inputText id="username" value="#{sessionInfoBean.currentUser.username}" disabled="true"/>
                        <p:outputLabel for="password" value="Password: " />
                        <p:password id="password" value="#{sessionInfoBean.currentUser.password}" disabled="true"/>

                        <p:outputLabel for="firstName" value="First Name: " />
                        <p:inputText id="firstName" value="#{sessionInfoBean.currentUser.firstName}"/>
                        <p:outputLabel for="firstName" value="Last Name: " />
                        <p:inputText id="lastName" value="#{sessionInfoBean.currentUser.lastName}"/>
                        <p:outputLabel for="email" value="E-Mail: " />
                        <p:inputText id="email" value="#{sessionInfoBean.currentUser.email}"/>
                        <p:outputLabel for="phone" value="Phone: " />
                        <p:inputMask id="phone" value="#{sessionInfoBean.currentUser.phone}" mask="+99? 999 9999999"/>
                        

                        <p:outputLabel for="design" value="Layout: "/>
                        <p:selectOneMenu id="design" value="#{userDetailController.design}" style="width: 170px">                            
                            <f:selectItems value="#{userDetailController.designs}" var="design" itemValue="#{design}" itemLabel="#{design}"/>
                        </p:selectOneMenu>
                        
                        <p:column />
                        <p:column>
                            <button type="submit" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
                                <span class="ui-button-text">Save changes</span>
                            </button>
                        </p:column>
                    </h:panelGrid>
                
            </p:panel>    
            
        </h:form>
        
    </ui:define>
</ui:composition>

src/main/webapp/secured/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:ng="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name ="content">
        <h:form id="screen">
            <p:panel header="Welcome to SMARD Timemanagement">
                <div>
                    An online tool to track used time for a project.
                </div>                
            </p:panel>
      
            <!--Project picker-->
            <p:panel style="padding-right: 100px">               
                    <h:panelGrid columns="2" cellpadding="5">
                    <p:column>
                        <p:outputLabel for="project" value="Work Packages:"/>
                    </p:column>            
                    <p:column>                                
                        <p:selectOneMenu id="project" value="#{workPackageDetailController.workPackageId}" style="width:300px" disabled="#{timeStampBean.hasOpenTimeStamp()}">                            
                            <f:selectItem itemLabel="Select work package" itemValue="#{null}" noSelectionOption="true"/>
                            <f:selectItems value="#{workPackageListController.packages}" var="work" itemValue="#{work.workPackageId}" itemLabel="#{work.workPackageName}"/>
                            <p:ajax process="@this" update="@(form)" listener="#{workPackageDetailController.loadWorkPackageWithId()}"/>   
                        </p:selectOneMenu>
                    </p:column>
                
        
        <!--Check buttons--> 
                    <p:row>
                        <p:commandButton value="Check in" id="checkInButton" style="width:150px" update="@(form)" actionListener="#{workPackageDetailController.checkIn}" disabled="#{timeStampBean.hasOpenTimeStamp()}"/> 
                        <p:commandButton value="Check out"  style="width:150px" update="@(form) show_project" actionListener="#{workPackageDetailController.checkOut}" disabled="#{!timeStampBean.hasOpenTimeStamp()}"/>
                    </p:row>
                </h:panelGrid>
            </p:panel>              
            <p:panelGrid columns="2" id="reminder" rendered="#{timeStampBean.hasOpenTimeStamp()}">
                <h:outputText value="Open Work Package: "/>
                <h:outputText value ="#{workPackageDetailController.openWorkPackageName}"/>
            </p:panelGrid>
        </h:form>
    </ui:define>
</ui:composition>