src/main/java/at/qe/sepm/skeleton/ui/beans/SessionInfoBean.java
package at.qe.sepm.skeleton.ui.beans;

import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.model.UserRole;
import at.qe.sepm.skeleton.services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;

/**
 * Session information bean to retrieve session-specific parameters.
 *
 * @author Michael Brunner <Michael.Brunner@uibk.ac.at>
 */
@Component
@Scope("session")
public class SessionInfoBean {

	@Autowired
	private UserService userService;

	/**
	 * Attribute to cache the current user.
	 */
	private User currentUser;

	/**
	 * Returns the currently logged on user, null if no user is authenticated
	 * for this session.
	 *
	 * @return
	 */
	public User getCurrentUser() {
		String currentUserName = getCurrentUserName();
		if (   currentUser == null
			|| currentUser.getUsername() != currentUserName) {
			if (currentUserName.isEmpty()) {
				return null;
			}
			currentUser = userService.loadUser(currentUserName);
		}
		return currentUser;
	}

	/**
	 * Returns the username of the user for this session, empty string if no
	 * user has been authenticated for this session.
	 *
	 * @return
	 */
	public String getCurrentUserName() {
		if (!isLoggedIn()) {
			return "";
		}
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		String name = auth.getName(); // get logged in username
		return name;
	}

	/**
	 * Returns the roles of the user for this session as space-separated list,
	 * empty string if no user has been authenticated for this session-
	 *
	 * @return
	 */
	public String getCurrentUserRoles() {
		if (!isLoggedIn()) {
			return "";
		}
		StringBuilder sb = new StringBuilder();
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		for (GrantedAuthority role : auth.getAuthorities()) {
			sb.append(role.getAuthority());
			sb.append(' ');
		}
		return sb.toString().trim();
	}

	/**
	 * Checks if a user is authenticated for this session.
	 *
	 * @return true if a non-anonymous user has been authenticated, false
	 *         otherwise
	 */
	public boolean isLoggedIn() {
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (auth != null) {
			return auth.isAuthenticated() && !auth.getName().equals("anonymousUser");
		} else {
			return false;
		}
	}

	/**
	 * Checks if the user for this session has the given role (c.f.
	 * {@link UserRole}).
	 *
	 * @param role
	 *            the role to check for as string
	 * @return true if a user is authenticated and the current user has the
	 *         given role, false otherwise
	 */
	public boolean hasRole(String role) {
		if (role == null || role.isEmpty() || !isLoggedIn()) {
			return false;
		}
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		for (GrantedAuthority ga : auth.getAuthorities()) {
			if (role.equals(ga.getAuthority())) {
				return true;
			}
		}
		return false;
	}

	public String getDesign(){
                
		return userService.getUserDesign(getCurrentUser());
	}
	
}

src/main/java/at/qe/sepm/skeleton/ui/beans/TimeStampBean.java
package at.qe.sepm.skeleton.ui.beans;

import at.qe.sepm.skeleton.model.TimeStamp;
import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.services.TimeStampService;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author daniel
 */

@Component
@Scope("request")
public class TimeStampBean {
    
    @Autowired
    private TimeStampService timeStampService;
    
    @Autowired
    private SessionInfoBean sessionInfo;
    
    public boolean hasOpenTimeStamp(){
            return hasOpenTimeStamp4User(sessionInfo.getCurrentUser());
    }
    
    public boolean hasOpenTimeStamp4User(User user){
        return timeStampService.getOpenTimeStamp4User(user) != null;
    }
    
    public TimeStamp getOpenTimeStamp(){
        return timeStampService.getOpenTimeStamp4User(sessionInfo.getCurrentUser());
    }
    
    public List<TimeStamp> getStamps4User(User user){
        return this.timeStampService.findByUser(user);
    }
}

src/main/webapp/WEB-INF/includes/footer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <body>
        <ui:composition>
            
            
            <div class="left">
                <ui:fragment id="show_project" rendered="#{sessionInfoBean.loggedIn and timeStampBean.hasOpenTimeStamp() and request.requestURI != '/secured/welcome.xhtml'}">
                    Open work package: #{timeStampBean.openTimeStamp.workPackage.workPackageName}
                </ui:fragment>
                <ui:fragment  rendered="#{sessionInfoBean.loggedIn and !timeStampBean.hasOpenTimeStamp() and request.requestURI != '/secured/welcome.xhtml'}">
                    No open work package
                </ui:fragment>
                <ui:fragment rendered="#{!sessionInfoBean.loggedIn}">
                </ui:fragment>
            </div>
            
            
            <div class="right">
                <ui:fragment rendered="#{sessionInfoBean.loggedIn}">
                    Logged in as #{sessionInfoBean.currentUserName} [#{sessionInfoBean.currentUserRoles}]
                </ui:fragment>
                <ui:fragment rendered="#{!sessionInfoBean.loggedIn}">
                    Not logged in
                </ui:fragment>
            </div>

        </ui:composition>
    </body>
</html>

src/main/webapp/WEB-INF/includes/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <body>
        <ui:composition>
            <h:form>
                <p:menubar>                    
                    
                    <p:menuitem value="Home" url="/secured/welcome.xhtml" rendered="#{sessionInfoBean.loggedIn}"/>
                    
                    <p:submenu label="Statistics" rendered="#{sessionInfoBean.loggedIn}">
                        <p:menuitem value="User Statistics" url="/student/user_statistics.xhtml"/>
                        <p:menuitem value="Group Statistics" url="/student/group_statistics.xhtml" rendered="#{sessionInfoBean.hasRole('MODERATOR')}"/>
                    </p:submenu>
                    <p:submenu label="Admin Settings" rendered="#{sessionInfoBean.hasRole('ADMIN')}">
                        <p:menuitem value="Manage Users" url="/admin/users.xhtml"/>
                        <p:menuitem value="Manage Teams" url="/admin/teams.xhtml"/>
                        <p:menuitem value="Manage Projects" url="/admin/projects.xhtml"/>
                        <p:menuitem value="Manage Timestamps" url="/admin/timestamps.xhtml"/>
                    </p:submenu>
                    <p:menuitem value="Settings" url="/secured/settings.xhtml" rendered="#{sessionInfoBean.loggedIn}"/>
                  
                    <p:menuitem value="Login" url="/login.xhtml" rendered="#{!sessionInfoBean.loggedIn}"/>
                    <p:menuitem value="Logout" class="logout" url="/logout" rendered="#{sessionInfoBean.loggedIn}"/>
                </p:menubar>

            </h:form>
        </ui:composition>
        

    </body>
</html>